//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OprioEntities : DbContext
    {
        public OprioEntities()
            : base("name=OprioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<FreeDomain> FreeDomains { get; set; }
        public DbSet<Invite> Invites { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemStatu> ItemStatus { get; set; }
        public DbSet<ItemStatusHistory> ItemStatusHistories { get; set; }
        public DbSet<ItemType> ItemTypes { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<OrganisationDomain> OrganisationDomains { get; set; }
        public DbSet<OrgPref> OrgPrefs { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PaymentFrequency> PaymentFrequencies { get; set; }
        public DbSet<PaymentMethod> PaymentMethods { get; set; }
        public DbSet<PaymentTerm> PaymentTerms { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonPref> PersonPrefs { get; set; }
        public DbSet<PersonSession> PersonSessions { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Relationship> Relationships { get; set; }
        public DbSet<RelationshipType> RelationshipTypes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<SubscriptionType> SubscriptionTypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TagPerson> TagPersons { get; set; }
        public DbSet<TagPersonItem> TagPersonItems { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketStatu> TicketStatus { get; set; }
        public DbSet<TicketType> TicketTypes { get; set; }
        public DbSet<Trackable> Trackables { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<vwPersonUser> vwPersonUsers { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    }
}
