//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
int ID {get; set; }
        public string Email { get; set; }
        public System.Guid InvitedByPersonID { get; set; }
        public System.Guid TagID { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
