//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
int ID {get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> NetInvoiceAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> GrossInvoiceAmount { get; set; }
        public System.DateTime InvoideDueDate { get; set; }
        public System.Guid AccountID { get; set; }
        public string Description { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.Guid> PaymentID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
