//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Files = new HashSet<File>();
            this.ItemStatusHistories = new HashSet<ItemStatusHistory>();
            this.Item1 = new HashSet<Item>();
            this.TagPersonItems = new HashSet<TagPersonItem>();
        }
    
int ID {get; set; }
        public string ItemText { get; set; }
        public Nullable<System.Guid> ParentItemID { get; set; }
        public byte ItemLevel { get; set; }
        public int ItemTypeID { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public Nullable<System.Guid> CreatorPersonID { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<ItemStatusHistory> ItemStatusHistories { get; set; }
        public virtual ICollection<Item> Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<TagPersonItem> TagPersonItems { get; set; }
        public virtual Trackable Trackable { get; set; }
    }
}
