//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStatu
    {
        public ItemStatu()
        {
            this.ItemStatusHistories = new HashSet<ItemStatusHistory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ItemTypeID { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<ItemStatusHistory> ItemStatusHistories { get; set; }
    }
}
