//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStatusHistory
    {
int ID {get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public int ItemStatusID { get; set; }
        public System.DateTime SetAtTimestamp { get; set; }
        public System.Guid SetByPersonID { get; set; }
        public string Value { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemStatu ItemStatu { get; set; }
        public virtual Person Person { get; set; }
    }
}
