//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        public ItemType()
        {
            this.Items = new HashSet<Item>();
            this.ItemStatus = new HashSet<ItemStatu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemStatu> ItemStatus { get; set; }
    }
}
