//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.OrganisationDomains = new HashSet<OrganisationDomain>();
            this.OrgPrefs = new HashSet<OrgPref>();
            this.People = new HashSet<Person>();
        }
    
int ID {get; set; }
        public string Name { get; set; }
        public System.DateTime SignupDate { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public string Handle { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<OrganisationDomain> OrganisationDomains { get; set; }
        public virtual ICollection<OrgPref> OrgPrefs { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
