//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Invites = new HashSet<Invite>();
            this.Items = new HashSet<Item>();
            this.ItemStatusHistories = new HashSet<ItemStatusHistory>();
            this.PersonPrefs = new HashSet<PersonPref>();
            this.PersonSessions = new HashSet<PersonSession>();
            this.Relationships = new HashSet<Relationship>();
            this.Relationships1 = new HashSet<Relationship>();
            this.Tags = new HashSet<Tag>();
            this.TagPersons = new HashSet<TagPerson>();
            this.TagPersons1 = new HashSet<TagPerson>();
            this.TagPersonItems = new HashSet<TagPersonItem>();
            this.Tickets = new HashSet<Ticket>();
        }
    
int ID {get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<System.Guid> OrganisationID { get; set; }
        public System.DateTime CreationTimeStamp { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Invite> Invites { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemStatusHistory> ItemStatusHistories { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PersonPref> PersonPrefs { get; set; }
        public virtual ICollection<PersonSession> PersonSessions { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<Relationship> Relationships1 { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<TagPerson> TagPersons { get; set; }
        public virtual ICollection<TagPerson> TagPersons1 { get; set; }
        public virtual ICollection<TagPersonItem> TagPersonItems { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
