//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSession
    {
        public System.Guid ConnectionID { get; set; }
        public System.Guid PersonID { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime ConnectTimestamp { get; set; }
        public Nullable<System.DateTime> DisconnectTimestamp { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
