//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPref
    {
int ID {get; set; }
        public System.Guid PersonID { get; set; }
        public string PrefKey { get; set; }
        public string PrefValue { get; set; }
        public string Description { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
