//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
int ID {get; set; }
        public System.Guid RelatingPersonID { get; set; }
        public System.Guid RelatedPersonID { get; set; }
        public int RelationshipTypeID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
    }
}
