//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public System.Guid SubscriptionID { get; set; }
        public System.Guid AccountID { get; set; }
        public int SubscriptionTypeID { get; set; }
        public decimal PriceUserMonth { get; set; }
        public int MinUsers { get; set; }
        public int MaxUsers { get; set; }
        public int UserCount { get; set; }
        public int MinTermMonths { get; set; }
        public bool IsRolling { get; set; }
        public int BaseStorageMB { get; set; }
        public int AdditinalStorageUserMB { get; set; }
        public int MaxConversationItems { get; set; }
        public string EnabledFeatures { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CreatedByPersonID { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid ModifiedByPersonID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CancellationCutoffDays { get; set; }
        public System.DateTime CancellationCutoffDate { get; set; }
        public bool IsTrial { get; set; }
        public Nullable<System.DateTime> TrialEndDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
    }
}
