//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Invites = new HashSet<Invite>();
            this.TagPersons = new HashSet<TagPerson>();
        }
    
int ID {get; set; }
        public string Name { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
        public System.Guid CreatorPersonID { get; set; }
        public bool IsConversation { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual ICollection<Invite> Invites { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<TagPerson> TagPersons { get; set; }
    }
}
