//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagPersonItem
    {
        public System.Guid TagPersonID { get; set; }
        public System.Guid ItemID { get; set; }
        public bool IsViewed { get; set; }
        public Nullable<System.DateTime> ViewedTimeStamp { get; set; }
        public System.Guid CreatorPersonID { get; set; }
        public System.DateTime CreationTimeStamp { get; set; }
        public int Rank { get; set; }
        public double Importance { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Person Person { get; set; }
        public virtual TagPerson TagPerson { get; set; }
    }
}
