//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagPerson
    {
        public TagPerson()
        {
            this.TagPersonItems = new HashSet<TagPersonItem>();
        }
    
int ID {get; set; }
        public System.Guid TagID { get; set; }
        public System.Guid PersonID { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
        public System.Guid CreatorPersonID { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public int Rank { get; set; }
        public double Importance { get; set; }
        public Nullable<System.DateTime> Pinned { get; set; }
        public Nullable<System.DateTime> Archived { get; set; }
        public Nullable<System.DateTime> Deferred { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual ICollection<TagPersonItem> TagPersonItems { get; set; }
    }
}
