//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
int ID {get; set; }
        public int TicketTypeID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string TicketRef { get; set; }
        public Nullable<System.Guid> PersonID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
