//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oprio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPersonUser
    {
        public System.Guid PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> OrganisationID { get; set; }
        public string Email { get; set; }
        public string RoleName { get; set; }
    }
}
